name: Format Check

on: [push, pull_request]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check .NET formatting
        run: dotnet format --verify-no-changes
      
      - name: Check JavaScript formatting
        run: npx prettier --check .
      
      - name: Enforce CSharpier formatting
        run: dotnet csharpier . --check